version: '3'
services:
  api:
    image: "game-react-node-docker-ts"
    build:
      dockerfile: Dockerfile
      context: ./api/
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://mongo:27017/trucks-db
      - JWT_SECRET=clientsecretToChange
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
